create table person
(
    id        integer generated by default as identity
        primary key,
    age       integer,
    firstname varchar(50),
    lastname  varchar(50)
);

alter table person
    owner to postgres;

create table species
(
    id          integer generated by default as identity
        primary key,
    common_name varchar(50),
    latin_name  varchar(200)
);

alter table species
    owner to postgres;

create table animal
(
    id         integer generated by default as identity
        primary key,
    color      varchar(50),
    name       varchar(50),
    sex        varchar(255),
    species_id integer
        constraint fk_species
            references species
);

alter table animal
    owner to postgres;

create table person_animals
(
    person_id  integer not null
        constraint fk_person_id
            references person,
    animals_id integer not null
        constraint fk_animals_id
            references animal,
    primary key (animals_id, person_id)
);

alter table person_animals
    owner to postgres;


